#!/bin/sh

. /etc/rc.common

stop() {
    . "/etc/live.conf"

    # Parse /proc/cmdline and override variables
    for arg in $(cat /proc/cmdline);do
        case "${arg}" in
            live_eject=[0-1]) LIVE_EJECT="${arg##*=}" ;;
        esac
    done

    if [ "${LIVE_EJECT}" = "1" ];then
        local boot_dev="$(cat /live/boot_device)"

        msg "Unmounting boot device"
        cmd umount -fl "${boot_dev}"

        msg "Ejecting boot device"
        cmd eject -T "${boot_dev}"

        warn "Press any key to continue"
        cmd read -s -n 1
    fi
}

case "$1" in
    start) ;;
    stop) stop ;;
esac
